
export const DELETE_REPLY = "DELETE_REPLY";
export const CHANGE_REPLY = 'CHANGE_REPLY';
export const ADD_NEW_REPLY = 'ADD_NEW_REPLY';
export const DELETE_LABEL = 'DELETE_LABEL';
export const CHANGE_LABEL = 'CHANGE_LABEL';
export const ADD_NEW_LABEL = 'ADD_NEW_LABEL';
export const GET_DEFAULT_REPLIES_STATE = 'GET_DEFAULT_REPLIES_STATE';
export const SELECT_USER = 'SELECT_USER';
export const ADD_USER_NOTES = 'ADD_USER_NOTES';
export const GET_DEFAULT_SELECTED_USER = 'GET_DEFAULT_SELECTED_USER';
export const GET_DEFAULT_USERS_NOTE = 'GET_DEFAULT_USERS_NOTE';
export const GET_DEFAULT_USERS_LABEL = 'GET_DEFAULT_USERS_LABEL';
export const GET_DEFAULT_USERS_CONNECTED_LABELS = 'GET_DEFAULT_USERS_CONNECTED_LABELS';